import React, { useEffect } from 'react'
import Head from 'next/head'
import axios from "axios"

import { Navbar } from "../components/navbar"
import { Footer } from '../components/footer'

import { MENU_ITEMS } from '../data/menu'
import { Planning } from '../components/planning'
import { HOST } from '../config'

const Horaires = (data) => {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1" />
            </Head>

            <Navbar menu={MENU_ITEMS} active={1}></Navbar>

            <main>
                <Planning title={"Horaires"} movies={data.movies}></Planning>
            </main>

            <Footer menu={MENU_ITEMS}></Footer>
        </>
    )
}


export default Horaires;

export async function getServerSideProps(ctx) {
    const nowPlayingReq = await axios.get(`${HOST}/api/movies?from=now_playing`);

    return {
        props: {
            movies: nowPlayingReq.data
        },
    };
};
