import { useEffect } from "react";
import Head from "next/head";
import { Navbar } from "../components/navbar";
import { Movies } from "../components/movies";
import { News } from "../components/news";
import axios from "axios";
import { Newsletter } from "../components/newsletter";
import { Footer } from "../components/footer";
import { HOST } from "../config";

export default function Home(data) {
  const MENU_LINKS = [
    {
      text: "Accueil",
      link: "/",
    },
    {
      text: "Horaires",
      link: "/horaires",
    },
    {
      text: "Films à l'affiche",
      link: "/films-a-l-affiche",
    },
    {
      text: "Prochainement",
      link: "/prochainement",
    },
    {
      text: "Informations",
      link: "/informations",
    },
    {
      text: "Mon compte",
      link: "/login",
    },
  ];

  useEffect(() => {
    // Make font-awesome css only load once page is fully loaded to avoid render-blocking
    document.getElementById("font-awesome").setAttribute("media", "all");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar menu={MENU_LINKS} active={0}></Navbar>

      <main>
        <section id="movies" style={{ backgroundColor: "#17192e" }}>
          <Movies
            title={"Films à l'affiche"}
            data={data.nowPlaying}
          ></Movies>
        </section>
        <section id="news">
          <News></News>
        </section>
        <section style={{ backgroundColor: "#17192e" }}>
          <Movies title={"Prochainement"} data={data.upcoming}></Movies>
        </section>
        <section id="newsletter">
          <Newsletter></Newsletter>
        </section>
      </main>
      <Footer menu={MENU_LINKS}></Footer>
    </>
  );
}


// Get upcomings and now playing movies
export async function getServerSideProps(ctx) {
  const nowPlayingReq = axios.get(`${HOST}/api/movies?from=now_playing`);
  const upcomingReq = axios.get(`${HOST}/api/movies?from=upcoming`);

  const [nowPlaying, upcoming] = await Promise.all([nowPlayingReq, upcomingReq]);

  return {
    props: {
      nowPlaying: nowPlaying.data,
      upcoming: upcoming.data,
    },
  };
};
