import { useEffect } from "react";
import Head from "next/head";

import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";
import { LoginForm } from "../components/loginform";

import { MENU_ITEMS } from "../data/menu";



export default function Login() {

    useEffect(() => {
        document.getElementById("font-awesome").setAttribute("media", "all");
    })


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1" />
            </Head>

            <Navbar menu={MENU_ITEMS} active={4}></Navbar>

            <main>
                <section id="login">
                    <LoginForm></LoginForm>
                </section>
            </main>

            <Footer menu={MENU_ITEMS}></Footer>
        </>
    )
}
