import { useEffect } from "react";
import Head from "next/head";
import { AuthProvider } from "../lib/firebaseAuth";

import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";

import { MENU_ITEMS } from "../data/menu";
import { RegisterForm } from "../components/registerform";
import { useRouter } from "next/router";
import useAuth from "../lib/firebaseAuth";



export default function Register() {

    const auth = useAuth();
    const router = useRouter();

    useEffect(() => {
        document.getElementById("font-awesome").setAttribute("media", "all");
    }, [])

    if (auth.user) {
        router.replace("/");
        return <></>
    } else {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1" />
                </Head>

                <Navbar menu={MENU_ITEMS} active={4}></Navbar>

                <main>
                    <section id="register">
                        <RegisterForm auth={auth}></RegisterForm>
                    </section>
                </main>

                <Footer menu={MENU_ITEMS}></Footer>
            </>
        )
    }
}
