import React from 'react'
import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../../../components/navbar'
import { Footer } from '../../../components/footer'
import { Movie } from '../../../components/movie'
import axios from "axios";
import { HOST } from '../../../config'

const Film = (data) => {

    const MENU_LINKS = [
        {
          text: "Accueil",
          link: "/"
        },
        {
          text: "Horaires",
          link: "/horaires"
        },
        {
          text: "Films à l'affiche",
          link: "/films-a-l-affiche"
        },
        {
          text: "Prochainement",
          link: "/prochainement"
        },
        {
          text: "Informations",
          link: "/informations"
        },
        {
          text: "Mon compte",
          link: "/login"
        },
      ]

      useEffect(() => {
        // Make font-awesome css only load once page is fully loaded to avoid render-blocking
        document.getElementById("font-awesome").setAttribute("media", "all");
      }, [])


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Navbar menu={MENU_LINKS} active={-1}></Navbar>

            <main>
                <Movie data={data.movie} trailer={data.trailerUrl}></Movie>
            </main>

            <Footer menu={MENU_LINKS}></Footer>

            <link href={"https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@300;400;700&display=swap"} rel="stylesheet" />
        </>
    )
}


export default Film;

export async function getServerSideProps(ctx) {
  const movieReq = axios.get(`${HOST}/api/movie?id=${ctx.query.id}`)
  const trailerReq = axios.get(`${HOST}/api/trailer?id=${ctx.query.id}`)

  const [movie, trailerUrl] = await Promise.all([movieReq, trailerReq]);

  return {
    props: {
      movie: movie.data,
      trailerUrl: trailerUrl.data
    },
  }
}